### ISSUE TITLE
Export lattices as 3MF format ?

### ISSUE THREAD

**Issue by yvanblanchard** [tpms-lattice/ASLI#5]
Since lattices mesh can be very costly using traditional mesh formats (stl, obj), a very convenient way could be to export data as 3MF Manufacturing format (lattice beams). Is it planned ?

**Comment by tpms-lattice** [comment]
I want to introduce support for it at some point since it tends to produce smaller files. However, it will not be supporting the 'beam lattice extension' nor benefiting from its advantages. This because ASLI was primarily intended to be used with lattices that are best defined with implicit functions and not parametrically. Beam latices would fall into the latter category. While ASLI can still create such lattices, the underlying mechanism does not rely on end-point vertices and radiuses to define the structure which, if I am not mistaken, is how beam structures are stored in 3MF files when making use of the beam lattice extension.
